## < All Credits Goes To DarkBoy For Making This Bot > ##
## Main bot Config ##
mainprefix: '%' # Main Prefix 
token: 'NzYyMDM5Nzc5NDE2MDgwNDI0.X3jW2Q.xtk_tkO-EDXA4r_eerhYKEs5xuw' # Token of your bot
status: '%help' # ur bot status
## Join Support Guild: https://discord.gg/devs  ##
